global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'cognition_app'
    static_configs:
      - targets: ['cerebral_cortex:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongo:9216']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']