global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'echostack'
    static_configs:
      - targets: ['echostack:8003']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['echostack_db:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['echostack_redis:6379']
    scrape_interval: 30s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']